const ExportStrategy = require('./ExportStrategy');

/**
 * PDF Export Strategy - Concrete Strategy implementation
 * Generates a structured representation of data for PDF conversion.
 * 
 * Note: In a production system, this would use a library like PDFKit or jsPDF-node.
 * For this academic project, it demonstrates the Strategy Pattern by providing
 * a unique implementation of the export interface.
 */
class PDFExportStrategy extends ExportStrategy {
  /**
   * Export data to PDF format
   * @param {Array} data - Data to export
   * @param {Object} options - Export options (title, headers, etc.)
   */
  async export(data, options = {}) {
    const { title = 'Exported Report', headers = [] } = options;

    if (!data || data.length === 0) {
      return this._generatePDFHeader(title) + '\nNo data records found.';
    }

    const columnHeaders = headers.length > 0 ? headers : Object.keys(data[0]);
    
    let content = this._generatePDFHeader(title);
    content += `\nTotal Records: ${data.length}\n`;
    content += `\n${'-'.repeat(80)}\n`;
    content += `| ${columnHeaders.map(h => String(h).padEnd(15)).join(' | ')} |\n`;
    content += `| ${'-'.repeat(78)} |\n`;

    data.forEach(item => {
      const row = columnHeaders.map(h => {
        const val = String(item[h] || '').substring(0, 15);
        return val.padEnd(15);
      }).join(' | ');
      content += `| ${row} |\n`;
    });

    content += `${'-'.repeat(80)}\n`;
    content += `\nGenerated by Design Pattern Final Project\n`;

    return content;
  }

  _generatePDFHeader(title) {
    return `[PDF DATA STREAM - FORMATTED REPORT]\nTITLE: ${title}\nDATE: ${new Date().toLocaleString()}\n`;
  }

  getContentType() {
    return 'application/pdf';
  }

  getFileExtension() {
    return 'pdf';
  }
}

module.exports = PDFExportStrategy;
